### ISSUE TITLE
Images can't be found

### ISSUE THREAD

**Issue by pvpoli** [robocorp/example-windows-calculator#1]
Hi
I am new to using Robot Framework to test desktop applications. I am trying to run your exemple and I'm getting errors on the second task as the images can't be found. I imported your code direct to Robocorp Lab by the "Open in Robocorp Lab" buton on the Simple Window Calculator Bot page (https://robocorp.com/portal/robot/robocorp/example-windows-calculator).

It seems Robocorp Lab is looking for the images in a temporary folder of its own creation (log below). 

I'm not sure if this is the right place to open this issue. Excuse me and please let me know if this is indeed the wrong place.

Cheers

KEYWORD Calculate using image locators
Start / End / Elapsed:	20211029 16:27:36.564 / 20211029 16:27:42.285 / 00:00:05.721
00:00:02.669KEYWORD Open the Calculator
00:00:03.049KEYWORD RPA.Desktop . Click alias:9
Documentation:	
Click at the element indicated by locator.

Start / End / Elapsed:	20211029 16:27:39.235 / 20211029 16:27:42.284 / 00:00:03.049
16:27:39.235	INFO	Resolving locator: alias:9	
16:27:39.236	INFO	Searching for image 'C:\Users\MyUser\AppData\Local\robocorp\RobocodeLab\temp\65_771654_369737500_1\workarea617c04cb\.images\9-path.png' (region: display, confidence: 92.0)	
16:27:39.710	INFO	Found 0 matches	
16:27:39.749	INFO	Resolving locator: alias:9	
16:27:39.750	INFO	Searching for image 'C:\Users\MyUser\AppData\Local\robocorp\RobocodeLab\temp\65_771654_369737500_1\workarea617c04cb\.images\9-path.png' (region: display, confidence: 92.0)	
16:27:40.065	INFO	Found 0 matches	
16:27:40.255	INFO	Resolving locator: alias:9	
16:27:40.257	INFO	Searching for image 'C:\Users\MyUser\AppData\Local\robocorp\RobocodeLab\temp\65_771654_369737500_1\workarea617c04cb\.images\9-path.png' (region: display, confidence: 92.0)	
16:27:40.603	INFO	Found 0 matches	
16:27:40.757	INFO	Resolving locator: alias:9	
16:27:40.758	INFO	Searching for image 'C:\Users\MyUser\AppData\Local\robocorp\RobocodeLab\temp\65_771654_369737500_1\workarea617c04cb\.images\9-path.png' (region: display, confidence: 92.0)	
16:27:41.060	INFO	Found 0 matches	
16:27:41.269	INFO	Resolving locator: alias:9	
16:27:41.270	INFO	Searching for image 'C:\Users\MyUser\AppData\Local\robocorp\RobocodeLab\temp\65_771654_369737500_1\workarea617c04cb\.images\9-path.png' (region: display, confidence: 92.0)	
16:27:41.608	INFO	Found 0 matches	
16:27:41.779	INFO	Resolving locator: alias:9	
16:27:41.780	INFO	Searching for image 'C:\Users\MyUser\AppData\Local\robocorp\RobocodeLab\temp\65_771654_369737500_1\workarea617c04cb\.images\9-path.png' (region: display, confidence: 92.0)	
16:27:42.097	INFO	Found 0 matches	
16:27:42.284	FAIL	TimeoutException: No matches found for: alias:9

**Comment by cmin764** [comment]
Hi, we deprecated Robocorp Lab in favor to our de facto solution: VSCode + Robocorp extension.

A few articles to help here:
- https://robocorp.com/docs/developer-tools/visual-studio-code
- [Image Locators](https://robocorp.com/docs/development-guide/locators/image)

And our AI-driven chatbot: [ReMark](https://chat.robocorp.com/)
